#!/bin/bash
# Copyright (c) 2013-2018 CIYAM Developers

if [ ! -f .bitcoin/bitcoin.conf ]; then
 if [ ! -d .bitcoin ]; then
  mkdir .bitcoin
 fi
 echo "rpcpassword=none">.bitcoin/bitcoin.conf
fi
./bitcoind &
