#!/bin/bash
# Copyright (c) 2012 CIYAM Open Developers

if [ $# -lt 1 ]; then
 echo "Usage: getpriv [public key]"
else
 password=`./scrypt dec password`
 echo $password | xclip
 echo GPG passphrase is now on the clipboard...
 sleep 2

 gpg --decrypt $1 | grep Privkey | cut -b 10- >x
 cat x | xclip
 rm x
 echo "Private key for $1 is now on the clipboard..."
fi

