#!/bin/bash
# Copyright (c) 2012-2018 CIYAM Developers

./hash_pwd
password=`xclip -o`

if [ ! -d Desktop ]; then
 mkdir Desktop
fi

echo "Building ZBar, Bitcoin and Vanitygen while generating GPG keys..."
./build-zbar &
./build-bitcoin &
./build-vanitygen &
g++ -o w w.cpp &

if [ ! "$1" = "restore" ]; then
 tmp=$HOME/x

 echo "%echo Generating the master key..." >$tmp
 echo "Key-Type: DSA" >>$tmp
 echo "Key-Length: 1024" >>$tmp
 echo "Subkey-Type: ELG-E" >>$tmp
 echo "Subkey-Length: 1024" >>$tmp
 echo "Name-Real: tux master" >>$tmp
 echo "Name-Email: tux@domain.net" >>$tmp
 echo "Expire-Date: 0" >>$tmp
 echo "Passphrase: $password">>$tmp

 gpg --batch --gen-key $tmp
 rm $tmp
fi

gpg --batch --gen-key gen-key.info

gpg --armor --export local >local.pub.gpg
./qr local.pub.gpg

if [ ! "$1" = "restore" ]; then
 gpg --armor --export tux >tux.pub.gpg
 ./qr tux.pub.gpg

 gpg --armor --export-secret-key tux >tux.sec.gpg
 split -b 1024 -d tux.sec.gpg tux.sec.gpg.
 ls -1 tux.sec.gpg.0* | xargs -n1 ./qr
fi

