#!/bin/bash
# Copyright (c) 2012 CIYAM Open Developers

./hash_pwd

echo "Building ZBar, Bitcoin and Vanitygen while generating GPG keys..."
./build-zbar &
./build-bitcoin &
./build-vanitygen &
g++ -o w w.cpp &

password=`xclip -o`
password="${password%?}"

echo "%echo Generating the master key..." >x
echo "Key-Type: DSA" >>x
echo "Key-Length: 1024" >>x
echo "Subkey-Type: ELG-E" >>x
echo "Subkey-Length: 1024" >>x
echo "Name-Real: tux master" >>x
echo "Name-Email: tux@domain.net" >>x
echo "Expire-Date: 0" >>x

gpg --batch --passphrase $password --gen-key x
rm x

gpg --batch --gen-key gen-key.info

gpg --armor --export tux >tux.pub.gpg
./qr tux.pub.gpg

gpg --armor --export-secret-key tux >tux.sec.gpg
split -b 1024 -d tux.sec.gpg tux.sec.gpg.
ls -1 tux.sec.gpg.0* | xargs -n1 ./qr

