#!/bin/bash
# Copyright (c) 2013-2018 CIYAM Developers

if [ $# -lt 1 ]; then
 echo "Usage: signtx [address or private key] [[image file]]"
else
 address=$1

 echo "Now scanning for the raw tx QR code..."
 if [ "$2" = "" ]; then
  ./zbarcam>raw_tx
 else
  ./zbarimg $2>raw_tx
 fi
 raw_tx=`cat raw_tx`

 if [ "${address:0:1}" -ne "1" ]; then
  pkey=$address
 else
  ./getpriv $address
  pkey=`xclip -o`
 fi
 echo "./bitcoind -rpc_password=none signrawtransaction $raw_tx '[\"$pkey\"]'" >txscript

 chmod a+x txscript
 ./txscript >~signtx
 rm txscript

 cat ~signtx | grep -o '"complete" : true' >x
 complete=`cat x | grep -o true`
 rm x

 if [ ! "$complete" = "true" ]; then
  cat ~signtx
  echo Error: Invalid tx or tx could not be completed.
 else
  cat ~signtx | grep -o 0100[0-9a-f]*0000 >send_tx
  ./qr send_tx
 fi

 rm ~signtx

fi

